module.exports = {
  TOKEN: "MASUKKAN_DISCORD_BOT_TOKEN_DISINI",
  CLIENT_ID: "MASUKKAN_CLIENT_ID_DISINI",
  FETCH_INTERVAL: 10000,
  EMBED_UPDATE_INTERVAL: 10000,
  DB_PATH: "./data/data.json",
  MAX_HISTORY_MS: 86400000
};
